# Site settings
title: littlemountainman
email: leon.hillmann@gymerg.de
description: "currenrly in the cloud - moving to VR soon"
baseurl: ""
url: "littlemountainman.github.io"
twitter_username: littlemtman
github_username:  littlemountainman
redirects: yes
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
exclude: [vendor]
